### PR TITLE
Fixed for ReferenceType and ASP.NET Core metapackage versioning

### PR DESCRIPTION
**Pull request by doggy8088**
The ASP.NET Core 2.1 Metapackage is about to change.   So I'd like to change the `prefix` to suffix 20 as a version.

Also, I fixed a tiny issue about the default value for ReferenceType property. Reference here: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

### CODE REVIEW

**Comment by tintoy** [comment]
Looks good! Will merge shortly.

**Comment by tintoy** [comment]
Just checking, by ReferenceType, do you mean RepositoryType?

**Comment by doggy8088** [comment]
Sorry, my bad.  It's RepositoryType for sure! :p

**Comment by tintoy** [comment]
I'll create a release once I'm finished with the default property value stuff

**Pull request merged**
