### PR TITLE
Bump language server to the latest commit

### PR DESCRIPTION
**Pull request by DoctorKrolic**
This bumps language server version to the latest commit, so it includes https://github.com/tintoy/msbuild-project-tools-server/pull/80 and https://github.com/tintoy/msbuild-project-tools-server/pull/81

@tintoy I think, we should make a release now. My original plan was to move server to .NET 8 first, but I faced an issue (possibly a .NET bug) and I am still investigating it. But nevertheless there were many changes, so IMO we should make a minor version release (`v0.5.0`). Possible changelog could be:
- Runtime, required to run the language server, is not acquired using `vscode-dotnet-runtime` extension as a dependency, so you don't need to have that specific version of .NET on your machine installed to use the extension
- All completion are now shown by default
- Basic integration with `redhat.vscode-xml` extension is now provided, so you can use its features for `msbuild` language
- Language server, packed with the extension, is now built in release mode
- Extension bundle size has been significantly optimized
- Dependencies have been updaded to address known security vulnerabilities

If you remember more changes, of course include them as well) Feel free to merge this without waiting for me. Also if you agree and gonna release new version, don't forget to make a git tag, so language server binaries are tagged with that version (https://github.com/tintoy/msbuild-project-tools-vscode/pull/131)

### CODE REVIEW

**Comment by tintoy** [comment]
Good plan! Will aim to get a new release out tonight :)

**Comment by tintoy** [comment]
@DoctorKrolic - can you try out this VSIX and let me know if it works for you?

[msbuild-project-tools-0.5.0.vsix.zip](https://github.com/tintoy/msbuild-project-tools-vscode/files/13439136/msbuild-project-tools-0.5.0.vsix.zip)

If so, will publish it to the gallery :)

**Comment by DoctorKrolic** [comment]
Yes, it works for me. Also checked assembly version and so on and everything there seems fine as well. We are good to go!

**Comment by tintoy** [comment]
Published :)

**Comment by tintoy** [comment]
Thanks for all your hard work BTW!

**Pull request merged**
