### PR TITLE
Use VS Code API to get configuration on the fly instead of keeping track of configuration changes ourselves

### PR DESCRIPTION
**Pull request by DoctorKrolic**
For some I guess historical reasons we were parsing our configuration into a singleton object and keeping track of configuration changes oursevles. I don't know how it was before, but I can definitely say that this is no longer needed since we can just ask for various pieces of configurations directly from VS Code API on the fly. This way we don't parse configuration sections that we are not interesed in on the client side and avoid the need to duplicate configuration definitions in `package.json` as VS Code configuration definitions and `settings.ts` as typescript interfaces. Also we can now drop `object-path` dependency from the resulting build

### CODE REVIEW

**Comment by tintoy** [comment]
I'm not sure about this change, to be honest - I feel like we're losing compile-time checking of the configuration schema by switching to untyped APIs (with no typing and hard-coded strings) for configuration. I can understand the desire not to use custom parsing/object paths, but I'm not sure we have enough logic (or enough tests) for validating that the configuration is valid that I'm entirely comfortable discarding the protection that typing gives us here.

I'm open to being convinced otherwise, though 🙂

**Comment by DoctorKrolic** [comment]
> we're losing compile-time checking of the configuration schema

I wouldn't call it "compile-time checking". Currently we create a variable of a known shape, copy everything from the configuration to it and just assume that all rules of the type shape are met. This gives us intellisense, but not much else. If we change configuration in `package.json`, we won't have any compile-time errors. And I very much dislike that _a design-time convenience_ has so many disadvantages, including _run-time side effects_: an additional dependency, the need to copy every config key even though we use only some of them, the need to keep in sync configuration schema in `package.json` and `settings.ts` and so on. At the same time from all use sites it is clear that we are reading a VS Code configuration and even though its keys are untyped in source files, we can easily see what is available to us just by looking into a corresponding section of `package.json` file

**Comment by tintoy** [comment]
Oh, yuck - I see the old implementation now (that deleted file is hidden by default in the PR).

So what happened was that originally, VS Code used to pass us an object graph representing our settings, but then at some point they decided to switch to passing individual settings instead. That code was an attempt to keep the existing logic rather than refactor every place we used the settings.

For what it's worth, I disagree about it being purely a design-time _convenience_; I consider it a design-time _guard rail_ if it helps the compiler to tell us (at the call site) when we've made a typo in a config key or treated a list like a single value (etc). But I agree the custom logic to rehydrate / select stuff from the config object-graph is not a great solution. So, ok, let's ditch it. At some point, I might want to revisit this, but for now I'm trying out ideas for the out-of-process MSBuild (i.e. other SDK/runtime) host.

**Review by tintoy — APPROVED** [review]

**Comment by tintoy** [comment]
Ah, I see they've made generic versions of the `getXXX` methods:

https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration

I might play around with that at some point (I'm bored and can find a way to auto-generate the config models from `package.json` definitions; i.e. not anytime soon).

**Pull request merged**
